### ISSUE TITLE
Supporting multiple logbooks (How it might be done)

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#242]
Supporting multiple logbooks within Cloudlog has something that's been bought up and mentioned more times than I can count, so I'm pondering the best way to perhaps support this idea.

At the moment all contacts are stored within `table_hrd_contacts_v01` which is completely fine and has worked well for longer than I can remember, there's a couple of ways to support multiple logbooks and ideas are the following.

- Generate a new `table_hrd_contacts_v01` when someone defines a logbook.
- Use a field within 'table_hrd_contacts_v01' such as `COL_STATION_CALLSIGN` or one of the undefined fields to store a `logbook_id`

Of course, adding these would require a fair amount of extra modifications, like allowing a user to select an active logbook, showing QSOs on all the views for the correct logbook and of course handling eQSL (syncing too in this case), LoTW, ADIF importing.

This isn't a priority at the moment but worth perhaps discussion.

Guess the biggest question is should it be explored or is setting up a new instance per logbook tolerable.

**Comment by Manawyrm** [comment]
I've been playing around with this idea/feature for a couple of days now. 
As you might've seen I've got a new callsign earlier this month. This required me to do a "fresh" start with the logbook in order to get a clean logbook.

My current idea for this would be to store the name of the logging table in the user table. 
So there's 2 users, DL4TMA and DO4TMA. The system automatically has table_hrd_contacts_dl4tma and table_hrd_contacts_do4tma and chooses the appropriate values at login. 

My (proof of concept) version just sets the $config['table_name'] at login to the username and ignores everything else. I'm not sure if this has any really bad side effects, but as far as I can tell, it works well and requires minimal changes.

One logging table per user seems to be a nice balance with very little work.
Mostly changes to the login code and some logic to create the tables required.

**Comment by magicbug** [comment]
Yes, I have the callsign issue, as the first M3PHP, then 2E0SQL but in between all that prefix changes for different radio trips so have about 8 installs its a pain!

I like the simple idea of doing just a simple config change on login, guess my main thing is to allow more than one user to login to a logbook. Agree the more we can limit changes the better, I guess one things that might be affected is eQSL logins and LoTW if they are on different account logins.

Those, however, could be pulled out the main user table and stored separately per logbook, this would also future proof for doing push things for Clublog, etc so that might be a good thing ultimately!

We could dump table_hrd style name and just call them "logbook_callsign" I see no reason not to keep things neater perhaps. 

Your method also means we keep consistent ADIF fields which I love that we are one of the few logging apps which do actually conform!

**Comment by dg9vh** [comment]
Would it be an idea to use the COL_STATION_CALLSIGN column and create filtered views on this?

**Comment by Manawyrm** [comment]
That could work, but I think I'd rather have "named" logbooks with their name in the users database. 
That also doesn't require any in-depth changes, just changing the global table name.

Filtering by callsign is quite a bit more work...

**Comment by dg9vh** [comment]
> That could work, but I think I'd rather have "named" logbooks with their name in the users database.

Ok, I think this could be done by adding an additional column in the log-table and selecting it via SQL when loading logbook.

By this way we also could have more than one logbook per user that could be switched.

**Comment by magicbug** [comment]
This is why I wondered about using the column COL_STATION_CALLSIGN its actually used in Station Profiles if you create one as you give it a callsign

**Comment by magicbug** [comment]
I think after some consideration the best route is via **_COL_STATION_CALLSIGN_** I've already implemented defining **Station Profiles** that are selected when saving a QSO, like @dg9vh points out this would just require a number of adjustments to SQL queries, would also remove the need for multiple tables.

Also the fact this is rapidly becoming the number one thing asked about.
