### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by kieranlee999** [magicbug/Cloudlog#2457]
So I've just upgraded using the master.zip again and now I'm getting the following errors: 

A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/maywcouk/public_html/Cloudlog/application/migrations/139_modify_eQSL_url.php:1)

Filename: core/Common.php

Line Number: 575

And

An uncaught Exception was encountered
Type: mysqli_sql_exception

Message: Duplicate entry 'version' for key 'option_name'

Filename: /home/maywcouk/public_html/Cloudlog/system/database/drivers/mysqli/mysqli_driver.php

Line Number: 301

**Comment by petrkr** [comment]
Which commit ID ?

master.zip varies during the time.

It seems like it trying run installer? Because only reason, why it would want add duplicate entry version for option_name could be that seed from install script for version 2 ( solved at issue #2443 and commit https://github.com/magicbug/Cloudlog/commit/fde3357d2ae4f0c4e841f00cfdb26d889cb4521b )

What version you had before ? I'll try simulate it.

**Comment by petrkr** [comment]
@kieranlee999 any update ?
