### ISSUE TITLE
Migration from PHP5 to PHP 7 no call information get from HamQTH/QRZ 

### ISSUE THREAD

**Issue by pa2eon** [magicbug/Cloudlog#275]
Dear Peter,
After the main upgrade off PHP 5.2 to PHP 7.2.x I can not fix the data recovery from HamQTH or QRZ.com.
No data is filled in anymore when you make a new QSO .. or fill in a done QSO later.
In the logs their is no kind of infromation what will be wrong.
You can test it yourself ... when you use the login parms I send by PE.

Also .. when you add a new call .. before the application had give a pop-up that the call was not used before / find before .. this pop-up is also gone .. 

vy '73, Eric / PA2EON

**Comment by magicbug** [comment]
I'm not sure what code base your using of Cloudlog it's changing rapidly and since just before Christmas there's been some big changes.

I'd check that login information for qrz or hamqth is provided in application/config/config.php I'd also suggest checking your server logs to see if that's errors from PHP. It does use JSON so this module must be installed but a bit beyond the scope of support due to the large number of Linux distributions
