### ISSUE TITLE
[PHP8.3] Creation of dynamic property CI_Cache::$file is deprecated

### ISSUE THREAD

**Issue by pa8s** [magicbug/Cloudlog#3146]
**Describe the bug**
Creation of dynamic property CI_Cache::$file is deprecated in libraries/Driver.php

```
ERROR - 2024-06-17 11:34:33 --> Severity: 8192 --> Creation of dynamic property CI_Cache::$file is deprecated /mnt/www/system/libraries/Driver.php 188
```

**To Reproduce**
Error message visible on main page (your.url/index.php) and in log file.

**Expected behaviour**
No error.

**Server**
OS: FreeBSD 13.1
Server: nginx/1.24.0
PHP: 8.3.8
Git branch: dev
Commit: https://github.com/magicbug/Cloudlog/commit/54dea657ec8e556600ea89c48d13bd16d5675a0f
Tag: [2.6.13-41-g54dea657](https://github.com/magicbug/Cloudlog/releases/tag/2.6.13)

**Additional context**
Issue mentioned [here](https://github.com/magicbug/Cloudlog/issues/2947#issuecomment-1961203152), created this issue to have it in focus.

**Comment by magicbug** [comment]
Aware, currently no fix is available

**Comment by petrkr** [comment]
How looks this one?
I just updated from 2.8.6 to 2.8.12 and I start getting this warning message on PHP 8.2

Now can not save QSO in development server, because it is in JSON response.

<img width="1255" height="316" alt="Image" src="https://github.com/user-attachments/assets/9d25c57a-0c38-4489-96c3-d3e56d29df88" />
