### ISSUE TITLE
Distance Chart stats page 

### ISSUE THREAD

**Issue by M0TZO** [magicbug/Cloudlog#384]
This is an idea for a chart to show distances worked.

Similar to the grid square page, maybe using grid squares to work out distances appropriately, per band, mode & overall.

**Comment by AndreasK79** [comment]
Are you thinking of something like this? [https://la8aja.com/distplot/](https://la8aja.com/distplot/)
This is something I wrote a while back. It uses the gridsquare for calculation. I might be able to implement something like this in Cloudlog.

![image](https://user-images.githubusercontent.com/6977712/74137011-627f5380-4bef-11ea-8340-330d00420928.png)

**Comment by magicbug** [comment]
Even if thats not what @M0TZO had in mind, i wouldn't mind that feature for searching my satellite QSOs to see distances :)

**Comment by AndreasK79** [comment]
@magicbug I'll see what I can do. It's mostly a matter of adapting the code to work with MVC in Cloudlog, so it's not a total rewrite.

**Comment by AndreasK79** [comment]
@magicbug I have a working concept:
![image](https://user-images.githubusercontent.com/6977712/74311538-02fc8180-4d70-11ea-8d88-b621b2ff4264.png)

I need to polish it up a little bit, but right now I have the code fetching all the bands in config. How do you select on satellite QSOs? Should I also assume that col_my_gridsquare is always set (just validate the gridsquare, as I do for gridsquares fetched from each qso)?

**Comment by magicbug** [comment]
prop_mode column when set to "SAT" will provide all satellite QSOs.

I'd use the grid square for the active profile for the "operators square" rather than any field from the qso table.

Within QSO there's two grid square fields ones `COL_GRIDSQUARE` which has just one square but if the QSO is for a grid line more than one square then it's stored in `COL_VUCC_GRIDS `this is the same for even VHF/UHF QSOs those in `COL_VUCC_GRIDS` if you look in `application/models/Gridsquares_model.php` you will find some example database stuff that I use for building the gridsquare maps.

**Comment by magicbug** [comment]
Just a follow on satellite name assigned to a qso is in COL_SAT_NAME
